apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vehicle-api-ingress
  namespace: connected-vehicle
spec:
  podSelector:
    matchLabels:
      app: vehicle-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: dashboard
      ports:
        - protocol: TCP
          port: 8000
    - ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vehicle-api-egress
  namespace: connected-vehicle
spec:
  podSelector:
    matchLabels:
      app: vehicle-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: telemetry-ingest
        - podSelector:
            matchLabels:
              app: trip-service
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # EKS Pod Identity Agent (link-local credential endpoint)
    - to:
        - ipBlock:
            cidr: 169.254.170.23/32
      ports:
        - protocol: TCP
          port: 80
