apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: connected-vehicle
data:
  AWS_REGION: "us-west-2"
  S3_BUCKET: "sandbox-eks-data-west"
  LAMBDA_FUNCTION: "sandbox-eks-processor"
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "INFO"
